### DISCUSSION TITLE
Can't see the settings / the skip button on Jellyfin web

### DISCUSSION THREAD

**Discussion by DameGAD** [intro-skipper/intro-skipper#537] [Q&A] [answered]
Hi everyone,

I'm trying to make the plugin work with the web version of Jellyfin, without success until now.

Here's my situation:
Jellyfin version: 10.10.7
Jellyfin installation method: docker, jellyfin/jellyfin.
Intro Skipper version: 1.10.10.20
Browser: tested on Firefox 139.0.4 & Brave 1.79.119 (not that I think it's important but we never know I guess)

What's working: The plugin is intalled, its settings are visible and if I enable "Server-side Auto Skip", it does work on jellyfin web. Skip buttons work on Findroid.
What's not working: on Jellyfin-web, I can't see the skip button. I also can't see any settings related to the plugin in Playback > Advanced. Same on the official mac app.

I ran a full analysis of my medias as well as the task "Media Segment Scan" as stated in the documentation, and after that I was able to test successfully the plugin on Findroid and auto-skip on jellyfin web.
The container originally didn't run with root permissions (I used an user dedicated to Jellyfin with "user: '1021:1021'" and "group_add" to give access to my medias). I removed these lines to run it as root (the troubleshooting page mentions it under "Obsolete troubleshooting" so I wasn't sure if it still can be useful). It didn't help after a restart of the container.
I also tried to use the default Dark theme instead of a custom one, without success. I should also mention that /jellyfin/jellyfin-web is mounted outside of the container volume in order to add my custom theme.

My docker-compose is as follow:
```
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: bridge
    volumes:
      - /ssd1/docker/jellyfin/config:/config
      - /ssd1/docker/jellyfin/cache:/cache
      - /ssd1/docker/jellyfin/jellyfin-web:/jellyfin/jellyfin-web
      - /volume1/medias/video:/video:ro
      - /volume1/medias/music:/music:ro
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - ROC_ENABLE_PRE_VEGA=1
    restart: unless-stopped
    ports:
      - 8096:8096
```

I'm asking help because I'm out of ideas to make it work on jellyfin-web.
